# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 827c46df791dce8a4809795c71d6326ee9ea871f2f2848f25d1a893e489ca1079ba3c174d6cef8f3e6cc7131b1d5d7592eecf7e6a23d205000736a8a4b7d566b

test:
  secret_key_base: de6aa58d395f3436d79dfdf8212fb8925507c8504dfc7a8a78edf00c5f7d502eee9581b3f412b872d7e7539fd8d19b17fcfa14dde08662bae9dd1514aa691b8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
